const deleteImgCtrl = {};
const path = require("path");
const fs = require("fs");
const { promisify } = require("util");

// This function deletes a image from the backend generated by any controller

deleteImgCtrl.deleteImg = async (nameImage) => {
  promisify(fs.unlink)(path.resolve(__dirname, "../storage/imgs", nameImage));
};

module.exports = deleteImgCtrl;
